### ISSUE TITLE
Player Controls not working

### ISSUE THREAD

**Issue by robertlj1209** [robertlj1209/game#4]
Added Player Controls and the console keeps on saying update is not defined. Which is at controls.update();

**Comment by PiusNyakoojo** [comment]
I've pushed the changes to fix this issue here at: https://github.com/robertlj1209/game/commit/b31ed27d4af154bf6d09c92e87389124c30600ea

Also made a few performance improvements using JavaScript objects instead of a list data structure to make retrieving players easier.

A few things to note about the fix:
- From my experience, the problem seemed to relate to the `socket.io` server not connecting with the browser client. Even though the `socket.io` registered a connection on the server side, the connection wasn't being registered on the browser. I tested this by calling `console.log('Hello World')` in the `socket.on('connect', . . )` callback function. The 'Hello World' message wasn't logged to the Firefox console as I had expected.
- Instead of using `socket.io`, the project is now using `ws` which is a similar websocket-based javascript library
- **For the issue relating to "controls.update()"**: The logic of the code seemed to be set up to require creating a player `createPlayer()` before loading the world `loadWorld()` so that `controls` can be initialized (and not be `undefined`) before being used with `controls.update()`. Because `createPlayer()` wasn't called, the `controls` variable wasn't initialized with the `new PlayerControls(camera, player)` command. Instead of fixing this directly by initializing the `controls` in the header of the `client_world.js` file, I replaced the `socket.io` dependency with a similar library called `ws` which helped to keep the code the same while only needing a new networking solution. 
- The player retrieval from a table is much faster than using a list that's iterated over to find the property or object that you're looking for. (for example, finding a player in the `players` list was replaced with `playerTable` which makes indexing the location of player easier than looking through the entire list using a for loop)

Things that should be working:
- starting the server using `npm run start`
- opening a browser tab and seeing a player join and being able to move around using the arrow keys
- opening a second browser and seeing the second browser player join the room where the first player is
- leaving the room by closing the browser tab

More notes:
- This is a nice starter project to help you get into multiplayer programming and video game development. It's also very useful if you're interested in video games for the web since the language being used is JavaScript (which is a widely adopted language for many web browsers).
- The project architecture (in terms of how the files and folders are organized) could be organized differently to make programming easier for you and other people that join the project later on.

Let me know if you need anything else! ❤️

**Comment by robertlj1209** [comment]
Omg thank you so much, so I’m making a web based RPGMMO and if you want I can add you to the discord that I have as a collaborator if you don’t mind.

If I do have any other issues your the man to call.

Yes I will have a lot at the Clean up thing thank you

Thanks Rob LJ
